# Generated by Django 2.0.6 on 2018-06-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandal', models.CharField(max_length=500)),
                ('gram_panchayat', models.CharField(max_length=500)),
                ('village', models.CharField(max_length=500)),
            ],
        ),
    ]
