# Generated by Django 2.0.6 on 2018-06-24 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GramPanchayat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gram_panchayat', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Mandal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandal', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=500)),
                ('gram_panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.GramPanchayat')),
                ('mandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.Mandal')),
            ],
        ),
        migrations.AlterField(
            model_name='constency',
            name='gram_panchayat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.GramPanchayat'),
        ),
        migrations.AlterField(
            model_name='constency',
            name='mandal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.Mandal'),
        ),
        migrations.AlterField(
            model_name='constency',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.Village'),
        ),
        migrations.AddField(
            model_name='grampanchayat',
            name='mandal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.Mandal'),
        ),
    ]
