# Generated by Django 2.0.6 on 2018-06-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0002_auto_20180624_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grampanchayat',
            name='mandal',
        ),
        migrations.RemoveField(
            model_name='village',
            name='gram_panchayat',
        ),
        migrations.RemoveField(
            model_name='village',
            name='mandal',
        ),
        migrations.AlterField(
            model_name='constency',
            name='gram_panchayat',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='constency',
            name='mandal',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='constency',
            name='village',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name='GramPanchayat',
        ),
        migrations.DeleteModel(
            name='Mandal',
        ),
        migrations.DeleteModel(
            name='Village',
        ),
    ]
