# Generated by Django 2.0.6 on 2018-06-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0004_auto_20180625_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grampanchayat',
            old_name='gram_panchayat',
            new_name='gp',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='gram_panchayat',
            new_name='gp',
        ),
    ]
