# Generated by Django 2.0.6 on 2018-06-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0005_auto_20180625_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grampanchayat',
            name='gp',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mandal',
            name='mandal',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='village',
            name='village',
            field=models.CharField(max_length=500),
        ),
    ]
