# Generated by Django 2.0.6 on 2018-06-25 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0006_auto_20180625_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('dob', models.DateField()),
                ('gram_panchayat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cm.GramPanchayat')),
                ('mandal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cm.Mandal')),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cm.Village')),
            ],
        ),
    ]
