# Generated by Django 2.0.6 on 2018-06-25 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0007_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_position', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='booth_number',
            field=models.CharField(default='booth_number', max_length=10),
        ),
        migrations.AddField(
            model_name='party',
            name='father_name',
            field=models.CharField(default='father_name', max_length=500),
        ),
        migrations.AddField(
            model_name='party',
            name='phone_number',
            field=models.CharField(default='phone_number', max_length=10),
        ),
        migrations.AddField(
            model_name='party',
            name='party_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cm.PartyPosition'),
        ),
    ]
