# Generated by Django 2.0.6 on 2018-06-25 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0008_auto_20180625_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gram_panchayat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cm.GramPanchayat')),
                ('mandal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cm.Mandal')),
                ('party_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cm.PartyPosition')),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cm.Village')),
            ],
        ),
    ]
