# Generated by Django 2.0.6 on 2018-06-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0010_auto_20180627_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
