# Generated by Django 2.0.6 on 2018-06-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0011_party_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
