# Generated by Django 2.0.6 on 2018-06-30 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0012_auto_20180630_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='phone_number',
            field=models.CharField(default='', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number should be up to 10 digits allowed or you can also write +91.', regex='^\\+?d{2}?\\d{10}$')]),
        ),
    ]
