# Generated by Django 2.0.6 on 2018-06-30 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0015_auto_20180630_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='phone_number',
            field=models.CharField(default='', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number should be up to 10 digits only', regex='^\\d{10}$')]),
        ),
    ]
