# Generated by Django 2.0.6 on 2018-07-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0016_auto_20180630_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='partydata/'),
        ),
    ]
