# Generated by Django 2.0.6 on 2018-07-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0017_auto_20180703_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='telguefile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf', models.FileField(upload_to='import/')),
            ],
        ),
    ]
