# Generated by Django 2.0.6 on 2018-07-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0019_auto_20180715_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smsapi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sam_api', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='telguefile',
        ),
    ]
