# Generated by Django 2.0.6 on 2018-07-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0020_auto_20180720_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsapi',
            name='sam_api',
            field=models.CharField(max_length=250),
        ),
    ]
