# Generated by Django 2.0.6 on 2018-07-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0023_party_caste'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='voter_id',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
