# Generated by Django 2.0.6 on 2018-07-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0024_party_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='booth_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='father_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=6, null=True),
        ),
    ]
