# Generated by Django 2.0.6 on 2018-08-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0027_partyfilter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='dob',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
