# Generated by Django 2.0.6 on 2018-08-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0028_auto_20180827_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='dob',
            new_name='age',
        ),
    ]
