# Generated by Django 2.0.6 on 2018-08-30 20:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cm', '0031_mpuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MPuser',
            new_name='MP_user',
        ),
    ]
