# Generated by Django 2.0.6 on 2018-08-30 20:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cm', '0032_auto_20180831_0151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MP_user',
            new_name='MP',
        ),
    ]
