# Generated by Django 2.0.6 on 2018-08-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0033_auto_20180831_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mp',
            name='user',
        ),
        migrations.DeleteModel(
            name='MP',
        ),
    ]
