# Generated by Django 2.0.6 on 2018-08-30 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cm', '0035_mp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp',
            name='Constensies',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mp',
            name='mp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MP', to=settings.AUTH_USER_MODEL),
        ),
    ]
