# Generated by Django 2.0.6 on 2018-08-30 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0036_auto_20180831_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp',
            name='mp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='MP', to=settings.AUTH_USER_MODEL),
        ),
    ]
